# Generated by Django 5.2.1 on 2025-11-10 20:07

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Үүсгэсэн огноо')),
                ('isPage', models.BooleanField(default=False, help_text='Энэ контентийг хуудсан дээр харуулах бол сонгоно уу', verbose_name='Хуудас эсэх')),
                ('isCarousel', models.BooleanField(default=False, help_text='Энэ контентийг карусель дээр харуулах бол сонгоно уу', verbose_name='Карусель эсэх')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контентууд',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ImportantURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Холбоосын нэр')),
                ('url', models.URLField(max_length=500, verbose_name='Холбоос')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Дараалал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Чухал холбоос',
                'verbose_name_plural': 'Чухал холбоосууд',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Таг',
                'verbose_name_plural': 'Тагууд',
            },
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Видеогийн гарчиг', max_length=200, verbose_name='Гарчиг')),
                ('url', models.URLField(blank=True, help_text='Гадаад видеогийн холбоос (YouTube, Facebook гэх мэт)', max_length=500, null=True, verbose_name='Видео холбоос')),
                ('video_file', models.FileField(blank=True, help_text='Видео файл оруулах (mp4, webm гэх мэт)', null=True, upload_to='videos/', verbose_name='Видео файл')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеонууд',
            },
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
            ],
            options={
                'verbose_name': 'Мэдээ',
                'verbose_name_plural': 'Мэдээнүүд',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest.content',),
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
            ],
            options={
                'verbose_name': 'Хуудасны контент',
                'verbose_name_plural': 'Хуудасны контентууд',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest.content',),
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_images/', verbose_name='Зураг')),
                ('text', models.TextField(blank=True, help_text='Зургийн тайлбар эсвэл гарчиг', verbose_name='Тайлбар')),
                ('order', models.IntegerField(default=0, help_text='Дараалал', verbose_name='Жагсаалтын дараалал')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rest.content', verbose_name='Холбогдсон контент')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннерууд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст агуулга')),
                ('order', models.IntegerField(default=0, verbose_name='Жагсаалтын дараалал')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='rest.content', verbose_name='Холбогдсон контент')),
            ],
            options={
                'verbose_name': 'Контентийн текст',
                'verbose_name_plural': 'Контентийн текстүүд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Дэд гарчиг')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('template', models.CharField(choices=[('standard', 'Энгийн'), ('homepage', 'Нүүр хуудас'), ('contact', 'Холбоо барих'), ('admissions', 'Элсэлт')], default='standard', max_length=50, verbose_name='Загвар')),
                ('is_published', models.BooleanField(default=True, verbose_name='Нийтлэгдсэн эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('parent', models.ForeignKey(blank=True, help_text='Хэрэв энэ нь дэд хуудас бол эцэг хуудсыг сонгоно уу', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rest.page', verbose_name='Эцэг хуудас')),
            ],
            options={
                'verbose_name': 'Хуудас',
                'verbose_name_plural': 'Хуудсууд',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='rest.page', verbose_name='Холбогдсон хуудас'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contents', to='rest.tag', verbose_name='Тагууд'),
        ),
    ]
