# Generated by Django 5.2.1 on 2025-05-24 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent page, if any', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rest.page'),
        ),
    ]
