# Generated by Django 5.2.1 on 2025-05-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_page_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='rest.page'),
        ),
    ]
