# Generated by Django 5.2.1 on 2025-05-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_content_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
