# Generated by Django 5.2.1 on 2025-05-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_content_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isPage',
            field=models.BooleanField(default=False, help_text='Indicates if this content is a page or not'),
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order of display')),
                ('link', models.URLField(blank=True, help_text='Optional link for the carousel item', null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='rest.content')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
