# Generated by Django 5.2.1 on 2025-06-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_content_ispage_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isCarousel',
            field=models.BooleanField(default=False, help_text='Indicates if this content is a carousel or not'),
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
