# Generated by Django 5.2.1 on 2025-06-01 21:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_content_iscarousel_delete_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttext',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text content'),
        ),
    ]
