# Generated by Django 5.2.1 on 2025-06-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_alter_contenttext_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttext',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
