# Generated by Django 5.2.1 on 2025-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_alter_contenttext_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the video', max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
