# Generated by Django 5.2.1 on 2025-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourl',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (mp4, webm, etc.)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videourl',
            name='url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube, Facebook, etc.)', max_length=500, null=True),
        ),
    ]
