# Generated by Django 5.2.1 on 2025-11-10 18:16

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Холбоосын нэр')),
                ('url', models.URLField(max_length=500, verbose_name='Холбоос')),
                ('category', models.CharField(blank=True, help_text='Жишээ нь: Нийгмийн сүлжээ, Хуудас, Гадаад линк гэх мэт', max_length=100, verbose_name='Ангилал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Дараалал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Чухал холбоос',
                'verbose_name_plural': 'Чухал холбоосууд',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
            ],
            options={
                'verbose_name': 'Мэдээ',
                'verbose_name_plural': 'Мэдээнүүд',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest.content',),
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
            ],
            options={
                'verbose_name': 'Хуудасны контент',
                'verbose_name_plural': 'Хуудасны контентууд',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest.content',),
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['title'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контентууд'},
        ),
        migrations.AlterModelOptions(
            name='contentimage',
            options={'ordering': ['order'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннерууд'},
        ),
        migrations.AlterModelOptions(
            name='contenttext',
            options={'ordering': ['order'], 'verbose_name': 'Контентийн текст', 'verbose_name_plural': 'Контентийн текстүүд'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Хуудас', 'verbose_name_plural': 'Хуудсууд'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Таг', 'verbose_name_plural': 'Тагууд'},
        ),
        migrations.AlterModelOptions(
            name='videourl',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видеонууд'},
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Үүсгэсэн огноо'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='content',
            name='isCarousel',
            field=models.BooleanField(default=False, help_text='Энэ контент карусель дээр байна уу?', verbose_name='Карусель эсэх'),
        ),
        migrations.AlterField(
            model_name='content',
            name='isPage',
            field=models.BooleanField(default=False, help_text='Энэ контент хуудсан дээр байна уу?', verbose_name='Хуудас эсэх'),
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='rest.page', verbose_name='Холбогдсон хуудас'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contents', to='rest.tag', verbose_name='Тагууд'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rest.content', verbose_name='Холбогдсон контент'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(upload_to='content_images/', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Дараалал', verbose_name='Жагсаалтын дараалал'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='text',
            field=models.TextField(blank=True, help_text='Зургийн тайлбар эсвэл гарчиг', verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='rest.content', verbose_name='Холбогдсон контент'),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Жагсаалтын дараалал'),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст агуулга'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо'),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Нийтлэгдсэн эсэх'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Хэрэв энэ нь дэд хуудас бол эцэг хуудсыг сонгоно уу', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rest.page', verbose_name='Эцэг хуудас'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дэд гарчиг'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('standard', 'Энгийн'), ('homepage', 'Нүүр хуудас'), ('contact', 'Холбоо барих'), ('admissions', 'Элсэлт')], default='standard', max_length=50, verbose_name='Загвар'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Нэр'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='videourl',
            name='title',
            field=models.CharField(help_text='Видеогийн гарчиг', max_length=200, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='videourl',
            name='url',
            field=models.URLField(blank=True, help_text='Гадаад видеогийн холбоос (YouTube, Facebook гэх мэт)', max_length=500, null=True, verbose_name='Видео холбоос'),
        ),
        migrations.AlterField(
            model_name='videourl',
            name='video_file',
            field=models.FileField(blank=True, help_text='Видео файл оруулах (mp4, webm гэх мэт)', null=True, upload_to='videos/', verbose_name='Видео файл'),
        ),
    ]
