# Generated by Django 5.2.1 on 2025-11-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_importanturl_newscontent_pagecontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importanturl',
            name='category',
        ),
    ]
