# Generated by Django 5.2.1 on 2026-05-07 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_remove_importanturl_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Үүсгэсэн огноо'),
        ),
        migrations.AlterField(
            model_name='content',
            name='isCarousel',
            field=models.BooleanField(default=False, help_text='Энэ контентийг карусель дээр харуулах бол сонгоно уу', verbose_name='Карусель эсэх'),
        ),
        migrations.AlterField(
            model_name='content',
            name='isPage',
            field=models.BooleanField(default=False, help_text='Энэ контентийг хуудсан дээр харуулах бол сонгоно уу', verbose_name='Хуудас эсэх'),
        ),
    ]
