# Generated by Django 5.2.1 on 2026-05-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_alter_content_created_at_alter_content_iscarousel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Гарчиг')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('icon', models.CharField(choices=[('graduation', 'Төгсөлт (graduation cap)'), ('teacher', 'Багш (chalkboard teacher)'), ('university', 'Их сургууль (university)'), ('book', 'Ном (book)'), ('star', 'Од (star)'), ('globe', 'Дэлхий (globe)')], default='graduation', max_length=50, verbose_name='Дүрс')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Дараалал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
            ],
            options={
                'verbose_name': 'Мэдээллийн карт',
                'verbose_name_plural': 'Мэдээллийн картууд',
                'ordering': ['order'],
            },
        ),
    ]
